### ISSUE TITLE
writeFile function freezes on Windows

### ISSUE THREAD

**Issue by cedricve** [balena-io-modules/resin-image-fs#46]
Hello,

I'm having issues when trying to write a file to an img (when running on Windows). I'm trying this into etcher, before flashing to the SD card, but the screen is freezing. It does work on  OSX. This is the source code I'm running:

      return imagefs.writeFile({
        image: fileUnzipped.name,
        partition: 1,
        path: 'wireless.conf',
      }, `update_config=1`);

When compiled etcher `make electron-develop`, it throws following error (but doesnt break the build) when compiling ext2fs. Not sure if it's related.

<img width="1133" alt="Screenshot 2020-01-06 at 16 13 14" src="https://user-images.githubusercontent.com/1546779/71827065-b0a8b080-309f-11ea-8b1e-f7de05e32c97.png">

**Comment by cedricve** [comment]
@jviotti would you have any idea, as you worked on this before?

**Comment by cedricve** [comment]
Did some more investigation and it indeed looks like this is causing to break the application. Due to this linking error resin-image-fs functions are not working. Also no prebuilt release is avallable from node-ext2fs for electron 6.0.4 (which latest etcher is using).

**Comment by jviotti** [comment]
@zvin This looks like an issue on ext2fs, right? Could it be affecting us as well, mainly given that the build doesn't break if the compilation errors happen on Windows?

**Comment by zvin** [comment]
@cedricve please try with npm 6.7.0

**Comment by cedricve** [comment]
Thanks Alexis, can you tell me which node version you are also using?

Kind regards,
Verstraeten Cédric

**Comment by zvin** [comment]
Any node >= 6 should work.
I've just tested on Windows 10 with node `v10.15.1` and npm `v3.10.10` with `npm i --build-from-source`

**Comment by cedricve** [comment]
Thanks, for testing. I was mistaken, I already used 6.7.0, and it failed. 

The problem is that Im recommended by etcher to use npm 6.7.0.

Can you confirm this also work with this version?  Not sure you use nvm, to quickly change the version..

Thanks for helping out, this means a lot for me and the community.

Kind regards,
Verstraeten Cédric

**Comment by zvin** [comment]
`npx npm@6.7.0 i --build-from-source` also works

**Comment by cedricve** [comment]
Thanks strange I might miss something.. not sure. Would you be able to share the build? or make this also available as a pckage under the release?

Kind regards,
Verstraeten Cédric

**Comment by zvin** [comment]
What are you trying to build? resin-image-fs or etcher ?
You can get built versions of node-ext2fs here https://github.com/balena-io/node-ext2fs/releases

**Comment by cedricve** [comment]
So im adding resin-image-fs as a dependency to etcher. Because im trying to edit a file on a specific partition. This is why in using nom 6.7.0

Yes but the release for node 6.7.0 is not there..

Kind regards,
Verstraeten Cédric

**Comment by zvin** [comment]
`resin-image-fs` is already a dependency of etcher:
```
balena-etcher@1.5.70
└─┬ etcher-sdk@2.0.15
  └── resin-image-fs@5.0.8
```

You can import it in Etcher's devtools console (press CTRL + SHIFT + i to make it appear).

I think you are confusing npm and node.

Etcher uses npm 6.7.0 for installing requirements and building, other versions may also work.
Etcher builds the native modules against the electron runtime (not node).

For building Etcher, in etcher's folder, delete the `node_modules` folder and run `make electron-develop` then `npm start`.

**Comment by cedricve** [comment]
﻿Thanks, sorry for confusing. Well still it is failing at ext2fs (hence the linking error) with the electron runtime which is currently version 6, I believe.

So not sure whats missing I installed all the required plugins (make).

Any idea what I can do? Would it make sense to make available the ext2fs build for electron 6 runtime.

Kind regards,
Verstraeten Cédric

**Comment by zvin** [comment]
This is not possible currently.
You'll need to either make it build or extract it from an Etcher release.
It's in `resources/app.asar`, you can list and extract files from asar archives with https://www.npmjs.com/package/asar

**Comment by cedricve** [comment]
Sorry for spamming this issue, but still when doing this, I get the linking errors. Any idea what could be missing?

> npx npm@6.7.0 i --build-from-source

**Comment by cedricve** [comment]
> This is not possible currently.
> You'll need to either make it build or extract it from an Etcher release.
> It's in `resources/app.asar`, you can list and extract files from asar archives with https://www.npmjs.com/package/asar

Thanks for helping out! I will try it out.

Is it enough then to copy paste it inside the node_modules/ext2fs, and run make electron-build again?

**Comment by zvin** [comment]
Most probably but I haven't tried.

**Comment by cedricve** [comment]
> Most probably but I haven't tried.

will keep you posted, thank you so much. keep you posted.

**Comment by cedricve** [comment]
thanks @zvin, I did copy the .node files from the extracted app.asar, and now it's working properly. 
This hack made it work.

However I'm still wondering, why the compilation (linking) is not working on my Win10 installation. All the other native builds (other than ext2fs) work properly. It must that this library requires something I dont have.

**Comment by cedricve** [comment]
Hey @zvin, so this is where I am. I tested yesterday, as you suggested, for replacing the ext2fs dir from the app.asar file. I confirm this is working in development mode.

However when doing make electron-build this will not work as it will do the compilation again (and thus overide the ext2fs dir again). 

It looks like I need to fix the build anyway. I have been looking arround but feel a bit hopeless. I got everything installed from MinGW (gcc + make). But still not working.

The only new discovery is that at the end of link (when receiving the linker error). I also receive this warning. Does this mean something to you?

    ..\deps\e2fsprogs\lib\ext2fs\libext2fs.a : warning LNK4272: library machine type 'X86' conflicts with tar
    get machine type 'x64' [C:\tesst\node_modules\ext2fs\build\bindings.vcxproj]
    C:\tesst\node_modules\ext2fs\build\Release\bindings.node : warning LNK4088: image being generated due to
    /FORCE option; image may not run [C:\tesst\node_modules\ext2fs\build\bindings.vcxproj]

**Comment by zvin** [comment]
@cedricve I don't remember seeing this message.
If it helps, here is the output of `npm i` for `node-ex2fs` on my Windows 10 x64 computer:
```
> ext2fs@1.0.31 install C:\balena\node-ext2fs
> prebuild-install || node-gyp rebuild
alexis@WINDOWS-NUC C:\balena\node-ext2fs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  Copying Makefile...          1 fichier(s) copié(s).
  Building libext2fs...  mingw32-make: Entering directory 'C:/balena/node-ext2fs/deps/e2fsprogs/lib/ext2fs'
  mingw32-make: Nothing to be done for 'all'.  mingw32-make: Leaving directory 'C:/balena/node-ext2fs/deps/e2fsprogs/lib/ext2fs'
  win_delay_load_hook.cc  Generating code
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.  Finished generating code
  ext2fs.vcxproj -> C:\balena\node-ext2fs\build\Release\\ext2fs.node  ext2fs.vcxproj -> C:\balena\node-ext2fs\build\Release\ext2fs.pdb (Full PDB)
  node_ext2fs.cc  async.cc
  js_io.cc
  bindings.cc
..\src\js_io.cc(65): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\balena\node-ext2fs\build\bindings.vcxproj]
  C:\balena\node-ext2fs\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\src\node_ext2fs.cc(832): warning C4293: '<<': shift count negative or too big, undefined behavior [C:\balena\node-ext2fs\build\bindings.vcxproj]
..\src\node_ext2fs.cc(865): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\balena\node-ext2fs\build\bindings.vcxproj]
  C:\balena\node-ext2fs\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
  win_delay_load_hook.cc
     Creating library C:\balena\node-ext2fs\build\Release\bindings.lib and object C:\balena\node-ext2fs\build\Release\bindings.exp
libext2fs.a(mkjournal.o) : error LNK2001: unresolved external symbol __imp_htonl [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : error LNK2001: unresolved external symbol __imp_ntohl [C:\balena\node-ext2fs\build\bindings.vcxproj]
C:\balena\node-ext2fs\build\Release\bindings.node : warning LNK4088: image being generated due to /FORCE option; image may not run [C:\balena\node-ext2fs\build\bindings.vcxproj]
  Generating code
  All 531 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
libext2fs.a(closefs.o) : warning LNK4049: locally defined symbol _time64 imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(inode.o) : warning LNK4049: locally defined symbol _time64 imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : warning LNK4049: locally defined symbol _time64 imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(ext_attr.o) : warning LNK4049: locally defined symbol _time64 imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : warning LNK4049: locally defined symbol _errno imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : warning LNK4049: locally defined symbol _fstat64 imported [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : error LNK2019: unresolved external symbol __imp_htonl referenced in function ext2fs_create_journal_superblock.part.5 [C:\balena\node-ext2fs\build\bindings.vcxproj]
libext2fs.a(mkjournal.o) : error LNK2019: unresolved external symbol __imp_ntohl referenced in function ext2fs_add_journal_device [C:\balena\node-ext2fs\build\bindings.vcxproj]
C:\balena\node-ext2fs\build\Release\bindings.node : warning LNK4088: image being generated due to /FORCE option; image may not run [C:\balena\node-ext2fs\build\bindings.vcxproj]
  bindings.vcxproj -> C:\balena\node-ext2fs\build\Release\\bindings.node
  bindings.vcxproj -> C:\balena\node-ext2fs\build\Release\bindings.pdb (Full PDB)
```

`mingw32-make --version`:
```
GNU Make 4.2.1
Built for x86_64-w64-mingw32
```

**Comment by cedricve** [comment]
Interesting I got this. Explains a lot..

mingw32-make --version

<img width="597" alt="Screenshot 2020-01-08 at 20 36 26" src="https://user-images.githubusercontent.com/1546779/72009651-9b29b700-3256-11ea-81c9-d4ef21064c1c.png">


How did you install mingw32-make, usiing Mingw installer?

**Comment by cedricve** [comment]
Ok, so found the difference. I was based on the CONTRIBUTING.md file of Etcher. Which states that MinGW should be installed (https://github.com/balena-io/etcher/blob/master/docs/CONTRIBUTING.md). With a link to mingw.com.

This doesn't work for libext2fs. I installed mingw64 instead, and this gives me the exact same output as your. Thank you! I just tested changing a partition with resin-image-fs, and it works now.

Will now try to run the electron-build of etcher. I will try to make a PR for the contribution afterwards, although I think it's worth it to also add it to the README of this repo.

**Comment by zvin** [comment]
\o/ @cedricve 
Just to confirm, so I can close this issue: does `writeFile` work as expected on Windows for you now  ?

**Comment by cedricve** [comment]
yes It looks great now, it just complains now about tiffuttil, I disabled this on Linux before, but wondering where I can find this for Windows.. (didn't had this before).

**Comment by lurch** [comment]
IIRC tiffutil is only needed for the OSX builds?

**Comment by cedricve** [comment]
Actually it is here that it crashes: https://github.com/balena-io/etcher/blob/master/Makefile#L109.
Both Linux and Windows will crash on this. What I disabled it, because it gets executed everytime.

I will close this issue as I was able to make it build, and confim it is now working. The resolutio was to install mingw64 (http://mingw-w64.org/doku.php) and msys64. On top of that I had to install a couple of plugins for msys: difftools, make. Also curl, jq and sha256 were missing. 

I will come back with a PR.

@jviotti @zvin thanks for everything. We will need to improve/update to contribution section, if we would like more people to contribute to etcher. You can find Kerberos Etcher overhere: https://github.com/kerberos-io/etcher. Latest release has been uploaded, you can check it out ;)

**Comment by lurch** [comment]
> Actually it is here that it crashes: https://github.com/balena-io/etcher/blob/master/Makefile#L109.
Both Linux and Windows will crash on this.

Yeah, maybe I should have been more verbose in my previous message - it tries to run `tiffutil` (on line 109) because `assets/dmg/background.tiff` is missing. And it's only trying to make `assets/dmg/background.tiff` in the first place, because line 111 says that it's a dependency of `electron-build`. However `assets/dmg/background.tiff` is _actually_ only needed if you're running `electron-build` on OSX.
(technically, you could call this a 'bug' in Etcher's `Makefile`)

:slightly_smiling_face:

**Comment by cedricve** [comment]
thanks for clarification @lurch, I was just expecting you are creating builds using the exact same code base (with or without the .tiff) file.

**Comment by lurch** [comment]
I've not been building Etcher myself, I've not done any work on it for a couple of years.
I'm just a keen community member who likes to help out where he can by replying to GitHub issues :wink:
