### ISSUE TITLE
Bump ext2fs for Node 13 compatibility

### ISSUE THREAD

**Issue by pdcastro** [balena-io-modules/resin-image-fs#47]
As requested downstream in: balena-io/balena-cli/issues/1591

**Comment by renesy** [comment]
In [package.json](https://github.com/balena-io-modules/resin-image-fs/blob/master/package.json#L50) the ext2fs dependency is specified with: `"ext2fs": "^1.0.28"`. Therefore the latest 1.0.31 is used when resin-image-fs is installed directly.
